"use client";

import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import { Card, CardHeader, RowIcon } from "@/components/ui/finexy";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";
import { useAuth } from "@/context/AuthContext";
import { findClient, findUser, formatDate, formatDateTime, reportScopeLabel } from "@/lib/mock/helpers";
import { useData } from "@/lib/mock/store";
import { FileSpreadsheet } from "lucide-react";

export default function ReportHistoryPage() {
  const { currentUser } = useAuth();
  const { state } = useData();
  const role = currentUser?.role ?? "broker";

  const reports = state.reports.filter((r) => {
    if (role === "administrator" || role === "manager") return true;
    if (role === "broker") return state.clients.find((c) => c.id === r.clientId)?.brokerId === currentUser?.id;
    return r.clientId === currentUser?.clientId;
  });

  return (
    <div>
      <PageBreadcrumb pageTitle="Report History" />
      <Card>
        <CardHeader title="Report History" />
        <div className="mt-[15px]">
          <Table>
            <TableHeader>
              <TableRow>
                <TableCell isHeader>Type</TableCell>
                <TableCell isHeader>Client</TableCell>
                <TableCell isHeader>Scope</TableCell>
                <TableCell isHeader>Period</TableCell>
                <TableCell isHeader>Generated By</TableCell>
                <TableCell isHeader>Generated</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.length === 0 && (
                <TableRow>
                  <TableCell className="text-secondary">No reports generated yet.</TableCell>
                </TableRow>
              )}
              {reports.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="whitespace-nowrap">
                    <span className="flex items-center gap-[12px]">
                      <RowIcon>
                        <FileSpreadsheet size={16} strokeWidth={1.5} />
                      </RowIcon>
                      {r.type === "claims_history" ? "Claims History" : "Performance"}
                    </span>
                  </TableCell>
                  <TableCell>{findClient(state, r.clientId)?.name}</TableCell>
                  <TableCell>{reportScopeLabel(r.scope, state.policies)}</TableCell>
                  <TableCell className="whitespace-nowrap">
                    {formatDate(r.periodStart)} — {formatDate(r.periodEnd)}
                  </TableCell>
                  <TableCell>{findUser(state, r.generatedById)?.name}</TableCell>
                  <TableCell className="whitespace-nowrap">{formatDateTime(r.generatedAt)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </Card>
    </div>
  );
}
